[versions]
#must stay in sync with kotlin and gradle major.minor versions:
#noinspection AndroidGradlePluginVersion
agp = "8.9.3"

kotlin = "2.1.21"
coroutines = "1.10.2"

gdx = "1.14.0"
discord = "v2.0.1"

jna = "5.17.0"
ktor = "3.2.3"
logback = "1.5.21"
clikt = "5.0.3"

purity = "1.3.2"
detekt = "1.23.8"

# tests
junit = "4.13.2"
mockito = "5.20.0"

#android
ktxCore = "1.16.0"
ktxRuntime = "2.10.3"
desugar = "2.1.5"


[libraries]
#note - thanks to the subproject problem Studio won't properly recognize what is used or not:

agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlinPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

purity-annotations = { group = "io.github.yairm210", name = "purity-annotations", version.ref = "purity" }

gdx = { group = "com.badlogicgames.gdx", name = "gdx", version.ref = "gdx" }
gdx-platform = { group = "com.badlogicgames.gdx", name = "gdx-platform", version.ref = "gdx" }
gdx-tools = { group = "com.badlogicgames.gdx", name = "gdx-tools", version.ref = "gdx" }
gdx-backend-desktop = { group = "com.badlogicgames.gdx", name = "gdx-backend-lwjgl3", version.ref = "gdx" }
gdx-backend-android = { group = "com.badlogicgames.gdx", name = "gdx-backend-android", version.ref = "gdx" }
gdx-backend-headless = { group = "com.badlogicgames.gdx", name = "gdx-backend-headless", version.ref = "gdx" }

discord = { group = "com.github.MinnDevelopment", name = "java-discord-rpc", version.ref = "discord" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-websockets = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
ktor-client-contentnegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }

ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-server-contentnegotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-websockets = { group = "io.ktor", name = "ktor-server-websockets", version.ref = "ktor" }

logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "clikt" }

jna = { group = "net.java.dev.jna", name = "jna", version.ref = "jna" }
jna-platform = { group = "net.java.dev.jna", name = "jna-platform", version.ref = "jna" }

android-ktx-core = { group = "androidx.core", name = "core-ktx", version.ref = "ktxCore" }
android-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }
android-ktx-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "ktxRuntime" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }


[bundles]
jna = ["jna", "jna-platform"]
ktor-client = [
    "ktor-client-core", "ktor-client-cio",
    "ktor-client-websockets", "ktor-client-encoding", "ktor-client-contentnegotiation",
    "ktor-serialization"
]
ktor-server = [
    "ktor-server-core", "ktor-server-netty",
    "ktor-server-websockets", "ktor-server-auth", "ktor-server-contentnegotiation",
    "ktor-serialization"
]


[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
purity = { id = "io.github.yairm210.purity-plugin", version.ref = "purity" }
