# Jobs to build the client and server app for various architectures
name: Build

on:
  # Triggers the workflow on any push or pull request
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - distribution: 'temurin'
            java_version: '11'
            os: ubuntu-latest
          - distribution: 'temurin'
            java_version: '11'
            os: macos-latest
          # Java 17 seems to be unsupported right now
          #- distribution: 'temurin'
          #  java_version: '17'
          #  os: ubuntu-latest
          #- distribution: 'temurin'
          #  java_version: '17'
          #  os: macos-latest
          - distribution: 'zulu'
            java_version: '11'
            os: ubuntu-latest
          - distribution: 'zulu'
            java_version: '11'
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java_version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.3

      - name: Compile kotlin and build classes
        run: ./gradlew classes

      - name: Run code checks
        run: ./gradlew check

      - name: Run unit tests
        run: ./gradlew --no-build-cache cleanTest test tests:test

      - name: Build the Desktop app
        run: ./gradlew desktop:dist

      - name: Build the Java server
        run: ./gradlew server:dist

      - name: Build Android debug files
        continue-on-error: true
        run: |
          mkdir whatsNewDirectory
          echo "Nothing changed so far" > whatsNewDirectory/whatsnew-en-US
          ./gradlew :android:bundleDebug
          ./gradlew :android:assembleDebug

      - name: Print all known files for debugging
        run: find | sort
