# Jobs to build the client and server app for various architectures
name: Build and test

on:
  # Triggers the workflow on any push or pull request
  push:
  pull_request:

jobs:
  build:
    name: Build for ${{ matrix.os }} (Java ${{ matrix.java_version }})
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        java_version:
          - 11
          - 17

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.0

      - name: Compile kotlin and build classes
        run: ./gradlew classes

      - name: Run code checks
        run: ./gradlew check

      - name: Run unit tests
        run: ./gradlew --no-build-cache cleanTest test tests:test

      - name: Build the Desktop app
        run: ./gradlew desktop:dist

      - name: Build the Java server
        run: ./gradlew server:dist

      - name: Build Android debug files
        continue-on-error: true
        run: |
          mkdir whatsNewDirectory
          echo "Nothing changed so far" > whatsNewDirectory/whatsnew-en-US
          ./gradlew :android:bundleDebug
          ./gradlew :android:assembleDebug

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Android
          path: android/build/outputs/apk/*/*.apk
          retention-days: 1

      - name: Upload Desktop artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Desktop
          path: desktop/build/libs/*.jar
          retention-days: 1

      - name: Upload Java server artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Server
          path: server/build/libs/*.jar
          retention-days: 1

  # Builds for Windows don't require extensive checks
  windows-build:
    name: Build for ${{ matrix.os }} (Java ${{ matrix.java_version }})
    defaults:
      run:
        # Ensures that a UNIX-like shell is available (default would be Powershell)
        shell: sh

    strategy:
      matrix:
        java_version:
          - 11
          - 17

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.0

      - name: Compile kotlin and build classes
        run: ./gradlew classes

      - name: Build the Desktop app
        run: ./gradlew desktop:dist

      - name: Build the Java server
        run: ./gradlew server:dist

      - name: Upload Desktop artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows Desktop
          path: desktop/build/libs/*.jar
          retention-days: 1
